travis:
  secure:
    BINSTAR_TOKEN: oxOcC+kljOBkRgS2M6W2Dq63oQ3KwC1WSrACU7F615FmdF+q4gAGnW9RfCwmqv/PA52MoO0WmddRHDe6lzj6e+vaBrYKqLXgESSdkE8cO8i9ARUhz9wzu/wwE+MLq0fyJIGV5qbQw3TZtWmH2WEBN2/KFGtSI0ni2MwPd0Dk1kxwulzhaUcv7nY6mCUaH/Gsmk9PSBUjTvwwbZ9C0T1anGnQsmaeq1DYh2t4MxWMaO4VtTImKC/+p3/TggEWxsMBJ48kRTRIjr456IrlAX4SIcXLZBwh4tWFYRERk1v7HaqJf4CtTiJbxOVNg7tvRUCKGoKjyyl8Sq5yEpyRq8Rvvwn5sisw8tyv84/RMxAw+bpNgsubzTWOFMx4uH0uJrkBNQEKeup61xwFHfgF1CLZrdZSK1SAfCLVjT6f29HPbfsMOVTbp8LmgirS9WjNCXT6gCPGsBAFBwlaigZAC5p6BHaVsLxcetnejY7mREysDXJU8IxitKmJ36Wk57O5ZyEgeziYr8z+XG015ypcU5oo2H07fs/+Hf9jbS91AT+EqBuhEPyhFRJuk3h/4QBUsjW0OlMu63CwbUAPsbYUnNwu696IRQoj+J+qHpZBi8RsbAEtjfV+Am2Lqt/Hdqaqv0XERYlIgVPpuV9AoxCSu/AWEYSf43cnjavs2ziwPpgkVtM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
